[book]
authors = ["Adam Perkowski"]
language = "en"
multilingual = false
src = "src"
title = "HighlightOS"

[output.html]
cname = "os.adamperkowski.dev"
default-theme = "highlight"
preferred-dark-theme = "highlight"
git-repository-url = "https://github.com/adamperkowski/highlightos"
edit-url-template = "https://github.com/adamperkowski/highlightos/edit/master/book/{path}"
additional-css = ["./theme/custom.css"]

[output.html.search]
use-boolean-and = true
