name: Github Pages

on:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - run: mdbook build book

  deploy:
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set output directory
        run: |
          OUTDIR=$(basename ${{ github.ref }})
          echo "OUTDIR=$OUTDIR" >> $GITHUB_ENV

      - name: Deploy stable
        uses: peaceiris/actions-gh-pages@v4
        if: startswith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
          destination_dir: ./${{ env.OUTDIR }}
