name: Rust

on:
  push:
    paths:
      - shell/**
    branches: [ "main" ]
  pull_request:
    paths:
      - shell/**
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:
    name: Build hlshell [bin] [dev]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-binutils
        working-directory: shell
        run: sh -c "$(curl -sS https://raw.githubusercontent.com/adamperkowski/highlightos/main/shell/setup.sh)"

      - name: Build hlshell [bin] [dev]
        working-directory: shell
        run: cargo objcopy -- -O binary target/boot.bin

  build-bin-re:
    name: Build hlshell [bin] [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-binutils
        working-directory: shell
        run: sh -c "$(curl -sS https://raw.githubusercontent.com/adamperkowski/highlightos/main/shell/setup.sh)"

      - name: Build hlshell [bin] [release]
        working-directory: shell
        run: cargo objcopy --release -- -O binary target/boot.bin

  lints:
    name: hlshell Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.70
        with:
          components: rustfmt, clippy
      
      - name: Run cargo fmt on hlshell
        working-directory: shell
        run: cargo fmt --all --check

      - name: Run cargo clippy on hlshell
        working-directory: shell
        run: cargo clippy

  tests:
    name: hlshell Tests
    runs-on: ubuntu-latest
    needs: [ build, build-re ]

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo tests
        working-directory: shell
        run: cargo test --verbose
