name: Rust

on:
  push:
    paths:
      - kernel/**
    branches: [ "main" ]
  pull_request:
    paths:
      - kernel/**
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:
    name: Build hlkernel [bin] [dev]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install bootimage
        working-directory: kernel
        run: cargo install bootimage

      - name: Build hlkernel [bin] [dev]
        working-directory: kernel
        run: cargo bootimage

  build-bin-re:
    name: Build hlkernel [bin] [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install bootimage
        working-directory: kernel
        run: cargo install bootimage

      - name: Build hlkernel [bin] [release]
        working-directory: kernel
        run: cargo bootimage --release

  checks:
    name: hlkernel Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      
      - name: Run cargo fmt on hlkernel
        working-directory: kernel
        run: cargo fmt --all --check

      - name: Run cargo clippy on hlkernel
        working-directory: kernel
        run: |
          cargo clippy -- -Dwarnings
          cargo clippy --release -- -Dwarnings
