name: Rust

on:
  push:
    paths:
      - shell/**
    branches: [ "main" ]
  pull_request:
    paths:
      - shell/**
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bin:
    name: Build hlshell [bin] [dev]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install bootimage
        working-directory: shell
        run: cargo install bootimage

      - name: Build hlshell [bin] [dev]
        working-directory: shell
        run: cargo bootimage

  build-bin-re:
    name: Build hlshell [bin] [release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, llvm-tools-preview

      - name: Install bootimage
        working-directory: shell
        run: cargo install bootimage

      - name: Build hlshell [bin] [release]
        working-directory: shell
        run: cargo +nightly bootimage --release

  lints:
    name: hlshell Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      
      - name: Run cargo fmt on hlshell
        working-directory: shell
        run: cargo fmt --all --check

      - name: Run cargo clippy on hlshell
        working-directory: shell
        run: cargo clippy
